# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks #open source repo, with built-in hooks
#     rev: v2.3.0
#     hooks:
#       - id: check-yaml   #  Ensures all YAML files are properly formatted and have no syntax errors. 
#       - id: end-of-file-fixer # Ensures every file ends with a newline, which is a good practice in codebases.
#       - id: trailing-whitespace #  Removes any trailing whitespace in files.

#   - repo: https://github.com/gruntwork-io/pre-commit #open source repo ,with built-in hooks
#     rev: v0.1.22
#     hooks:
#       - id: tflint   # a linter for Terraform code, to check for errors and enforce best practices.
#         args:
#           - "--module"  
#           - "--config=.tflint.hcl"
#       - id: terraform-validate  #checks the syntax and correctness of Terraform code.
#       - id: terraform-fmt   #automatically formats Terraform code to follow standard styling.

#   - repo: https://github.com/antonbabenko/pre-commit-terraform #open source repo ,with built-in hooks
#     rev: "v1.74.1"
#     hooks:
#       - id: terraform_tfsec # security scanner for Terraform code, to identify potential security issues.
#       - id: terraform_checkov #check for configuration vulnerabilities and compliance issues in Terraform code.


repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: tflint
      - id: terraform_tfsec

      - id: terraform-validate
